name: 'Build-Docker'
description: 'Build Module Docker'

inputs:
  module:  # pipeline module / tag
    description: 'Pipeline module to build'
    required: true
    type: string
    default: 'base_bionic'

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    -
      name: Download image artifacts
      uses: actions/download-artifact@v2
      with:
        path: /images
    -
      name: Load images
      run: |
        ls -1 /tmp/*.tar | xargs --no-run-if-empty -L 1 docker load -i
        docker images
      shell: bash
    -
      name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        file: ./singularity/${{ inputs.module }}/Dockerfile
        tags: ${{ inputs.module }}:latest
        outputs: type=docker,dest=/tmp/${{ inputs.module }}.tar
    -
      name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.module }}
        path: /tmp/${{ inputs.module }}.tar
