name: 'Build Docker'
description: 'Build Module Docker'

inputs:
  module:  # pipeline module / tag
    description: 'Pipeline module to build'
    required: true
    type: string
    default: 'base_bionic'

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    -
      name: Download image artifacts
      uses: actions/download-artifact@v2
      with:
        path: /tmp/images/
    -
      name: Load images
      run: |
        find /tmp/images/ -type f -name '*.tar' | xargs --no-run-if-empty -L 1 docker load -i || true
        docker images
      shell: bash
    -
      name: Build Image
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        push: false
        file: ./singularity/${{ inputs.module }}/Dockerfile
        tags: ${{ inputs.module }}:latest
    -
      name: Export
      run: |
        mkdir -p /tmp/images
        docker save --output /tmp/images/${{ inputs.module }}.tar ${{ inputs.module }}:latest
      shell: bash
    -
      name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.module }}
        path: /tmp/images/${{ inputs.module }}.tar
