name: 'Build-Docker'
description: 'Build Module Docker'

inputs:
  module:  # pipeline module / tag
    description: 'Pipeline module to build'
    required: true
    type: string
    default: 'base_bionic'

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        file: ./singularity/${{ inputs.module }}/Dockerfile
        tags: ${{ inputs.module }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
