name: 'Push Module'
description: 'Push Pipeline Module'

inputs:
  module:  # pipeline module / tag
    description: 'Pipeline module to push'
    required: true
    type: string
  username:
    required: true
    type: string
  password:
    required: true
    type: string
  tag:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    -
      name: Download image artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.module }}
        path: /tmp/images/
    -
      name: Load image
      run: |
        mkdir -p /tmp/images
        find /tmp/images/ -type f -name '*.tar' | xargs --no-run-if-empty -L 1 docker load -i || true
        docker images
      shell: bash
    -
      name: Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./singularity/${{ inputs.module }}/Dockerfile
        tags: |
          $${{ inputs.username }}/${{ inputs.module }}:${{ inputs.tag }}
