name: 'Build-Docker'
description: 'Build Module Docker'

inputs:
  module:  # pipeline module / tag
    description: 'Pipeline module to build'
    required: true
    type: string
    default: 'base_bionic'
  username:
    required: true
    type: string
  password:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    -
      name: Load Images
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        file: ./singularity/${{ inputs.module }}/Dockerfile
        tags: user/${{ inputs.module }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
