name: 'Build-Docker'
description: 'Build Module Docker'

inputs:
  module:  # pipeline module / tag
    description: 'Pipeline module to build'
    required: true
    type: string
    default: 'base_bionic'
  username:
    required: true
    type: string
  password:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    -
      name: Download image artifacts
      uses: actions/download-artifact@v2
      with:
        path: /tmp/images/
    -
      name: Load images
      run: |
        mkdir -p /tmp/images
        find /tmp/images/ -type f -name '*.tar' | xargs --no-run-if-empty -L 1 docker load -i || true
        docker images
      shell: bash
    -
      name: Install pipeline
      run: |
        sudo apt-get install -y --no-install-recommends \
                build-essential libssl-dev uuid-dev libgpgme11-dev \
                libseccomp-dev pkg-config squashfs-tools
        pip install -r requirements.txt --upgrade
        snakemake --snakefile rules/install.smk --directory $HOME singularity
        export PATH=$HOME/bin:$PATH
      shell: bash
    -
      name: Test Image
      run: |
        python3 test/test_function.py DNA ${{ inputs.module }} $HOME/unit_tests --singularity
      shell: bash
    -
      name: Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        file: ./singularity/${{ inputs.module }}/Dockerfile
        tags: ${{ inputs.module }}:latest
