name: builds

on: [push, workflow_dispatch]

jobs:
  build-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - basecalling
          - alignment
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./singularity/${{ matrix.module }}/Dockerfile
          push: false
          tags: nanopype/${{ matrix.module }}:latest
