name: 'Build-Docker'
description: 'Build Module Docker'

on:
  workflow_call:
    inputs:
      module:  # pipeline module / tag
        description: 'Pipeline module to build'
        required: true
        type: string
        default: 'base_bionic'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./singularity/${{ inputs.module }}/Dockerfile
          push: false
          tags: nanopype/${{ inputs.module }}:latest
