name: ci

on: [push, workflow_dispatch]

jobs:
  build-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - base_bionic
          - build_bionic
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build-module
        uses: .github/actions/build-docker
        with:
          module: ${{ matrix.module }}
        secrets:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.TOKDOCKERHUB_TOKENEN }}
