name: ci

on: [push, workflow_dispatch]

jobs:
  # Baseline ubuntu image
  build-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build-module
        uses: ./.github/actions/build-docker
        with:
          module: base_bionic
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  # Module build environment
  build-builder:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build-module
        uses: ./.github/actions/build-docker
        with:
          module: build_bionic
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  # Module builder
  build-module:
    runs-on: ubuntu-latest
    needs: build-builder
    strategy:
      matrix:
        module:
          - basecalling
          - alignment
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build-module
        uses: ./.github/actions/build-docker
        with:
          module: ${{ matrix.module }}

  # Module tester
  test-module:
    runs-on: ubuntu-latest
    needs: build-module
    strategy:
      matrix:
        module:
          - basecalling
          - alignment
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build-module
        uses: ./.github/actions/test-docker
        with:
          module: ${{ matrix.module }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
